---

- name: Manage machine user
  user:
    name: "{{ machine_user.name }}"
    password: "{{ machine_user.password | default(omit) }}"
    comment: "{{ machine_user.comment | default(omit) }}"
    uid: "{{ machine_user.uid | default(omit) }}"
    groups: "{{ machine_user.groups | default([machine_user.name]) }}"
    shell: "{{ machine_user.shell | default('/bin/bash') }}"
    

- name: Manage ssh keys
  authorized_key:
    user: "{{ machine_user.name }}"
    key: "{{ item.key }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ machine_user.authorized_keys | default([]) }}"
